"use client";
import { useSandbox } from "@/contexts/SandBoxContext";
import { useState } from "react";

// ResponseDisplay component - displays the response generated by the model
const ResponseDisplay = () => {
  const { state } = useSandbox();
  const [copied, setCopied] = useState(false);

  const copyToClipboard = (text: string) => {
    if (!text) return;
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  return (
    <div className="mt-4">
      <h2 className="text-xl font-bold mb-2">Response:</h2>
      <div className="p-4 bg-gray-100 min-h-20 rounded max-h-[50vh] overflow-y-auto relative text-gray-800">
        <pre className="whitespace-pre-wrap break-words">
          {state.response.content}
        </pre>
        {state.response.metadata && (
          <button
            onClick={() => copyToClipboard(state.response.content)}
            className="absolute top-2 right-2 text-gray-500 hover:text-gray-700"
          >
            📋
          </button>
        )}
        {copied && (
          <span className="absolute top-2 right-10 text-green-500">
            Copied!
          </span>
        )}
      </div>
      {state.response.metadata && (
        <div className="mt-4">
          <h3 className="text-lg font-semibold">Metadata:</h3>
          <pre className="p-4 bg-gray-100 rounded whitespace-pre-wrap break-words text-gray-800">
            {state.response.metadata}
          </pre>
        </div>
      )}
    </div>
  );
};

export default ResponseDisplay;
